### ISSUE TITLE
Thermia Calibra Cool 7 BW heatpump

### ISSUE THREAD

**Issue by renaatdb** [klejejs/ha-thermia-heat-pump-integration#78] opened 2024-05-03 14:09 UTC
Hello,
It seems that since the update to core-2024.5.0 the Thermia Calibra Cool integration (Generic x86-64) does not work anymore. Is this possible?
I did not change the Password and Thermia username.
[ha-thermia-heat-pump-integration](https://github.com/klejejs/ha-thermia-heat-pump-integration) 3.4.0
Removed the integration. But I cant install it no more.
https://online.thermia.se/
Credentials are invalid.!  Strange

Regards

**Comment by klejejs** [comment] 2024-05-03 16:33
What kind of error do you see in the Home Assistant logs?

**Comment by renaatdb** [comment] 2024-05-03 16:48
Logger: custom_components.thermia_water_heater.config_flow
Bron: custom_components/thermia_water_heater/config_flow.py:52
integratie: thermia_water_heater
Eerst voorgekomen: 17:05:39 (2 gebeurtenissen)
Laatst gelogd: 18:44:29

Expecting value: line 1 column 1 (char 0)

**Comment by renaatdb** [comment] 2024-05-03 16:51
![image](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/5012211/df2c58eb-4f09-4dd7-a58d-db45658fdd4e)

**Comment by bramv101** [comment] 2024-05-05 12:24
Same problem here - credentials are invalid, while on the thermia webpage those work perfectly

**Comment by renaatdb** [comment] 2024-05-17 13:36
I see 2 files in the custom_componets folder
Thermia_water_heater and Thermia.
Can this be the proiblem?
Regards

**Comment by poblom** [comment] 2024-05-19 17:35
I have the same problem!

"Credentials are invalid" when I attempt to set up the integration. Had it working well for couple of month when suddenly was said to be "unavailable".  "Failed to set up" when reloading.

My credentials for thermia.online work well. I even made a new password to no avail.

A pity I deleted the integration meaning I can't turn on debug logging. The only message the log provides is the same as in the post above.

```
Logger: custom_components.thermia_water_heater.config_flow
Source: custom_components/thermia_water_heater/config_flow.py:52
integration: thermia_water_heater
First occurred: May 18, 2024 at 9:33:55 PM (5 occurrences)
Last logged: 7:27:17 PM

Expecting value: line 1 column 1 (char 0)
```

Could it be that the credentials are not sent!!

**Comment by poblom** [comment] 2024-06-10 12:47
Is there anyone actually looking at this issue? 
Anything I can do myself?
/POB

**Comment by klejejs** [comment] 2024-06-15 21:40
Hey! The error message did not help much as it seems to be a generic Python JSON parsing error. I have updated the integration to show clearer error messages to help me pinpoint the issue. Please try with the latest version and send me the logs including the error.

**Comment by renaatdb** [comment] 2024-06-16 08:08
Hey,
I tried again.
Same log
```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.thermia_water_heater.config_flow
Bron: custom_components/thermia_water_heater/config_flow.py:52
integratie: thermia_water_heater
Eerst voorgekomen: 10:01:12 (2 gebeurtenissen)
Laatst gelogd: 10:03:08

Expecting value: line 1 column 1 (char 0)
```
Thanks

**Comment by poblom** [comment] 2024-06-16 19:36
Problem solved! Sorry for the noise!
I was able to somehow set up the integration again. Done some clean-up in the custom_components folder and could "start over", sort of. What the problem was in the first place I really don't know (a corrupt file?) So, all good, works like before but I miss "Operational Status". What's happened to it?

**Comment by klejejs** [comment] 2024-06-16 19:39
@poblom as mentioned in [3.3.0 release notes](https://github.com/klejejs/ha-thermia-heat-pump-integration/releases/tag/3.3.0):

> Operational status entity is removed as it is generally incorrect and was never showing a correct value. Please use operational status values for different elements to figure out the heat pump state.

**Comment by klejejs** [comment] 2024-06-16 19:44
@renaatdb just to be sure, could you please try with the latest release again just to make sure it was not an issue related to API? 🙏🏻

**Comment by renaatdb** [comment] 2024-06-17 07:47
@klejejs 
```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.thermia_water_heater.config_flow
Bron: custom_components/thermia_water_heater/config_flow.py:52
integratie: thermia_water_heater
Eerst voorgekomen: 09:42:29 (2 gebeurtenissen)
Laatst gelogd: 09:44:16

Expecting value: line 1 column 1 (char 0)
```

Same issue
Thanks

**Comment by klejejs** [comment] 2024-06-27 13:27
I am hearing the issue could be due to an agreement that needs to be accepted in online portal, for those who get "Credentials are invalid", that should be accepted first and then the issue might disappear.

@renaatdb If the issue is present only on one device, you could try reinstalling the integration on the other - could be that HA is caching the requests.

Unfortunately, I don't have the new smart price feature yet, so I cannot comment on that.

**Comment by buskjan** [comment] 2024-07-06 06:49
I logged in to the online portal, accepted the agreement. Then I reloaded the integration and now everything is working fine.

**Comment by renaatdb** [comment] 2024-07-06 07:50
> I am hearing the issue could be due to an agreement that needs to be accepted in online portal, for those who get "Credentials are invalid", that should be accepted first and then the issue might disappear.
> 
> @renaatdb If the issue is present only on one device, you could try reinstalling the integration on the other - could be that HA is caching the requests.
> 
> Unfortunately, I don't have the new smart price feature yet, so I cannot comment on that.

For me it looks verry promising to reduce costs with a variable rate.
I saw it appear with the new update of my Calibra Cool 7 BW. I am now testing this out.
![smartprice](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/5012211/7c6bde44-18ef-4910-908b-633d6c2868de)

**Comment by admlko** [comment] 2024-08-03 07:26
> I am hearing the issue could be due to an agreement that needs to be accepted in online portal, for those who get "Credentials are invalid", that should be accepted first and then the issue might disappear.

Thanks, this was my issue as well.

> Unfortunately, I don't have the new smart price feature yet, so I cannot comment on that.

I have been using the Smart Price feature for a year now with maximum Economy settings (both at 5). Haven't noticed any issues (running out of hot water) but on the other hand, I also cannot comment on any possible savings.

If anyone thinks they should have a device with Smart Price feature but cannot find it, please update your device firmware and it should appear. For that, you need a code to enable service menu on the device.
The service menu code is (at least for me): 718293

**Comment by klejejs** [comment] 2024-08-09 10:25
The underlying issue has been fixed, thus, closing the issue.
Regarding smart price, unfortunately, as I do not have it on my heat pump, I cannot test it and develop the integration for it. If it appears, I will definitely take a look.

**Closed by klejejs** 2024-08-09 10:25 UTC
